// Generated by CoffeeScript 1.9.0
(function() {
  var fizzBuzz;

  fizzBuzz = function(num) {
    if (num % 15 === 0) {
      console.log(num, "FizzBuzz");
    }
    if (num % 5 === 0) {
      console.log(num, "Buzz");
    }
    if (num % 3 === 0) {
      console.log(num, "Fizz");
    }
    if (num % 15 !== 0 && num % 5 !== 0 && num % 3 !== 0) {
      console.log(num);
    }
    if (num < 100) {
      return fizzBuzz(num + 1);
    }
  };

  fizzBuzz(1);

}).call(this);
